@host=http://localhost:5050

POST {{host}}/api/match
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiIyZjQyOGEzOS0yMDE1LTRlMjEtOTEwYy0wNDBjZjU4YjE2MDEiLCJpc3N1ZWRBdCI6MTc1Mzg4MTk4NCwiZXhwaXJlc0F0IjoxNzUzOTY4Mzg0LCJpYXQiOjE3NTM4ODE5ODR9.ZW_Pj21Bbf4YJNx5HIg1C6cwj95KWg-7bMSrqRF6TFU