@host=http://localhost:5050

POST {{host}}/api/match/28CF47A4/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJjMzcwMDUzYi1jODkzLTRkMTQtYjY2Ni1iMGMwYzUwNmEwYTAiLCJpc3N1ZWRBdCI6MTc1Mzg4MjE0NCwiZXhwaXJlc0F0IjoxNzUzOTY4NTQ0LCJpYXQiOjE3NTM4ODIxNDR9.pNgtf9wlkC3Q4js9AhMqQf1xKovADPMSWvkAfHTctfk