@host=http://localhost:5050

POST {{host}}/api/match/41E03A79/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NTkzOWQ3YS0yYmNmLTQ5NmEtOWZiMi0yNTgxNTU4MmEyYzUiLCJpc3N1ZWRBdCI6MTc0MzcxMTQ1OSwiZXhwaXJlc0F0IjoxNzQzNzk3ODU5LCJpYXQiOjE3NDM3MTE0NTl9.dS8NUJ8wzogYlEE0ja6KPjt7NJxQTh4Up081u9xLryY