@host=http://localhost:5050

POST {{host}}/api/match/28CF47A4/play
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiIyZjQyOGEzOS0yMDE1LTRlMjEtOTEwYy0wNDBjZjU4YjE2MDEiLCJpc3N1ZWRBdCI6MTc1Mzg4MTk4NCwiZXhwaXJlc0F0IjoxNzUzOTY4Mzg0LCJpYXQiOjE3NTM4ODE5ODR9.ZW_Pj21Bbf4YJNx5HIg1C6cwj95KWg-7bMSrqRF6TFU

{
    "symbolPosition": 2
}

###

POST {{host}}/api/match/28CF47A4/play
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJjMzcwMDUzYi1jODkzLTRkMTQtYjY2Ni1iMGMwYzUwNmEwYTAiLCJpc3N1ZWRBdCI6MTc1Mzg4MjE0NCwiZXhwaXJlc0F0IjoxNzUzOTY4NTQ0LCJpYXQiOjE3NTM4ODIxNDR9.pNgtf9wlkC3Q4js9AhMqQf1xKovADPMSWvkAfHTctfk

{
    "symbolPosition": 8
}