@host=http://localhost:5050

POST {{host}}/api/match
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJmZTFmZGIxMS0wZDkzLTRkZDUtYjM0YS04MDAyYjdiYmRjMjUiLCJpc3N1ZWRBdCI6MTc0MzcxMTM4OCwiZXhwaXJlc0F0IjoxNzQzNzk3Nzg4LCJpYXQiOjE3NDM3MTEzODh9.Q7km7Q0RWU6HgoKspuSbv4ETWsYj8dlW0oFCohG3Bx4