@host=http://localhost:5050

POST {{host}}/api/match
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJkNzYxNjg2NS1jODU4LTQ5ZTgtYmQ0Ni0wNDc2OWIyZmViMDkiLCJpc3N1ZWRBdCI6MTc0MDAzNDIzOSwiZXhwaXJlc0F0IjoxNzQwMDM3ODM5LCJpYXQiOjE3NDAwMzQyMzl9.WT8mmYTKDMOcAc5J54OZvx3qeu7XgNofcf-Ss9rvBdk