@host=http://localhost:5050

POST {{host}}/api/match
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzM4NTIwMjQzLCJleHAiOjE3Mzg1MjM4NDN9.4K-Kp5WLFiHquzLX8DJ5I7q8VxvhrbNzseUb4tYI3Ik