@host=http://localhost:5050

POST {{host}}/api/match/09D6E910/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJkNzYxNjg2NS1jODU4LTQ5ZTgtYmQ0Ni0wNDc2OWIyZmViMDkiLCJpc3N1ZWRBdCI6MTc0MDY4OTQzMywiZXhwaXJlc0F0IjoxNzQwNzc1ODMzLCJpYXQiOjE3NDA2ODk0MzN9.y-prgwNm17RdO44DgsUOyGrOb2flb0E0FUIq9mxW5u4