@host=http://localhost:5050

POST {{host}}/api/match/MXBHZ8AJ/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImlzc3VlZEF0IjoxNzM4ODMyMTE2LCJleHBpcmVzQXQiOjE3Mzg4MzU3MTYsImlhdCI6MTczODgzMjExNn0.9Qrfj5z4zF0QRSykujBr1gxlM4RzmjhIASd8WeZXFmQ