@host=http://localhost:5050

POST {{host}}/api/match/MXBHZ8AJ/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImlzc3VlZEF0IjoxNzM5MzA5MDkwLCJleHBpcmVzQXQiOjE3MzkzMTI2OTAsImlhdCI6MTczOTMwOTA5MH0.XhWO-bHzz_qkR3ulHTi_vXy9fc9mPMgAHzWLvWBKpjA