@host=http://localhost:5050

POST {{host}}/api/match/KUAWWK5C/play
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJmZTFmZGIxMS0wZDkzLTRkZDUtYjM0YS04MDAyYjdiYmRjMjUiLCJpc3N1ZWRBdCI6MTc0MjQ2MjgzMiwiZXhwaXJlc0F0IjoxNzQyNTQ5MjMyLCJpYXQiOjE3NDI0NjI4MzJ9.WPxxJYLDSx-zuUVxn8ozMy-w7-CrxCiIQ92YO0-KsBg

{
    "symbolPosition": 4
}

###

POST {{host}}/api/match/KUAWWK5C/play
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NTkzOWQ3YS0yYmNmLTQ5NmEtOWZiMi0yNTgxNTU4MmEyYzUiLCJpc3N1ZWRBdCI6MTc0MDY4OTU4MiwiZXhwaXJlc0F0IjoxNzQwNzc1OTgyLCJpYXQiOjE3NDA2ODk1ODJ9.SS9KmMO-haDX_HDefL8Hdbb98npMH8BfH0zOAloGRY8

{
    "symbolPosition": 5
}