@host=http://localhost:5050

POST {{host}}/api/register
Content-Type: application/json

{
    "name": "thirdbutnotforgotten",
    "email": "thirdestone@email.com",
    "password": "asdfa",
    "passwordConfirmation": "asdfa"
}